model = "Qwen/Qwen3-30B-A3B-Instruct-2507"
max_steps = 100
trajectory_strategy = "branching"
batch_size = 128
rollouts_per_example = 16

[wandb]
project = "hanabi-rl"
name = "hanabi-rl"
entity = "arturomf94-stele"

[sampling]
max_tokens = 128

[[env]]
id = "nph4rd/hanabi"

[inference.model]
enable_auto_tool_choice = true
tool_call_parser = "hermes"
