[project]
name = "hanabi"
description = "Hanabi game"
tags = ["multi-agent"]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "verifiers==0.1.8.post1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
